config/routes.rb
Rails.application.routes.draw do

  ##############################################################################
  # Frontend routes
  ##############################################################################

  # Homepage
  root 'frontend#homepage'

  # Article
  get '/:year/:month/:day/:slug' => 'frontend#article', as: 'frontend_article', action: 'show', constraints: {
    year: /\d{4}/,
    month: /\d{2}/,
    day: /\d{2}/
  }

  # Image
  get '/photos/:id' => 'frontend#image', as: 'frontend_image', action: 'show'

  get '/photos/(:volume)/(:number)' => 'frontend#images', as: 'frontend_images', constraints: {
    volume: /\d+/,
    number: /\d+/
  }

  # Section
  get '/:slug(/page/:page)' => 'frontend#section', as: 'frontend_section', constraints: {
    slug: /(news|world-and-nation|opinion|arts|sports|campus-life|fun|science)/
  }

  # Author
  get '/authors/:slug' => 'frontend#author', as: 'frontend_author'

  # Photo
  get '/photographers/:slug' => 'frontend#photographer', as: 'frontend_photographer'
  # Photo submission link temporary redirect
  get '/submitphoto', to: redirect('https://www.dropbox.com/request/DRmRaJGEr7LfVXUG2FHf', status: 302)
  # Caption submission link temporary redirect
  get '/submitcaption', to: redirect('https://docs.google.com/spreadsheets/d/1aoRyGfaOIK9WIMaktEO9G_LAyBKHs8VCPnMBVVhtyDs/edit?usp=sharing', status: 302)

  # Tag
  get '/tags/:slug(/:page)' => 'frontend#tag', as: 'frontend_tag'

  # Issue index and issue
  get '/issues' => 'frontend#issue_index', as: 'frontend_issue_index'
  get '/issues/(:volume)/(:number)' => 'frontend#issue', as: 'frontend_issue', constraints: {
    volume: /\d+/,
    number: /\d+/
  }
  get '/issues/(:volume)/(:number)/pdf' => 'frontend#issue_pdf', as: 'frontend_issue_pdf', constraints: {
    volume: /\d+/,
    number: /\d+/
  }

  # Ads manifest and relay
  get '/niceties/manifest' => 'frontend#ads_manifest', as: 'frontend_ads_manifest'
  get '/niceties/:id' => 'frontend#ads_relay', constraints: {id: /\d+/}, as: 'frontend_ads_relay'

  # RSS feed
  get '/feed' => 'frontend#feed', as: 'frontend_feed', defaults: {format: 'rss'}

  # Search
  get '/search/:type/(:query)(/page/:page)' => 'frontend#search', as: :frontend_search, defaults: {type: :articles}

  get '/:section_name/:id(/:slug)', controller: 'frontend_pieces', action: 'show_old_url', constraints: {id: /\d+/, section_name: /(news|world-and-nation|opinion|arts|sports|campus-life|fun|science)/}

  get '/:volume/:number/:archivetag' => 'frontend#legacy_article', constraints: {volume: /V\d+/, number: /N\d+/, archivetag: /[^\/]*\.html/}
  get '/:volume/:number/:parent/:archivetag' => 'frontend#legacy_article', constraints: {volume: /V\d+/, number: /N\d+/, parent: /.*/, archivetag: /.*\.html/}

  get '/:name', controller: 'frontend_static_pages', action: 'show', as: 'frontend_static_page', constraints: {name: /(ads(\/(index|schedule|policies|payment|adscontact))?)|(about(\/(index|contact|opinion_policy|comments|unpublish|copyright|publication_schedule|subscribe|special_projects|sponsors|donate|join|staff))?)/}

  get '/ads/adinfo', controller: 'frontend_static_pages', action: 'adinfo'
  get '/ads/adinfo/:advertiser_type', controller: 'frontend_static_pages', action: 'adinfo', as: 'frontend_adinfo', constraints: {advertiser_type: /[^.]*/}

  post '/update_mast', controller: 'frontend_static_pages', action: 'update_mast'

  ##############################################################################
  # API routes
  ##############################################################################

  namespace :api do
    get 'issue_lookup/:volume/:issue', action: 'issue_lookup'
    get 'article_as_xml/:id', action: 'article_as_xml'
    get 'newest_issue'
    get 'article_parts'
    get 'style_mapping'
  end

  ##############################################################################
  # Backend routes
  ##############################################################################

  scope '/admin' do
    if ENV['MAINTENANCE'].present?
      match '*path', via: [:get, :post, :patch, :delete, :put], to: 'static_pages#maintenance'
      match '/', via: [:get, :post, :patch, :delete, :put], to: 'static_pages#maintenance'
    end

    get '/', to: 'static_pages#admin_homepage', as: :admin_root

    resources :ads

    resources :homepages, only: [:index, :show, :update] do
      member do
        post 'mark_publish_ready'
        post 'duplicate'
        post 'publish'
      end

      collection do
        get 'new_submodule_form'
        get 'new_row_form'
        post 'new_specific_submodule_form'
        post 'create_specific_submodule'
        post 'create_new_row'
      end
    end

    resources :issues, only: [:index, :show, :create] do
      member do
        get 'upload_pdf_form'
        post 'upload_pdf'
        delete 'remove_pdf'
      end
    end

    resources :authors, only: [:new, :create, :edit, :update, :show, :index]

    resources :sections, only: [:new, :create, :edit, :update, :show, :index]

    resources :images, only: [:new, :create, :edit, :update, :destroy, :show, :index] do
      member do
        post 'publish'
        post 'unpublish'
        patch 'add_article'
        patch 'remove_article'
      end
    end

    resources :articles, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :drafts, only: [:index, :show, :update] do
        member do
          get 'revert'
          post 'publish'
          get 'below_fold_preview'
        end
      end

      member do
        patch 'update_rank'
        post 'unpublish'
      end

      collection do
        get 'below_fold_preview', controller: 'article_versions', action: 'below_fold_preview'
      end
    end

    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
    resources :users, only: [:index, :show, :edit, :update]

    get '/publish', controller: 'publishing', action: 'dashboard', as: 'publishing_dashboard'
    post '/publish', controller: 'publishing', action: 'publish'
  end
end

app/models/homepage.rb
class Homepage < AbstractModel
  serialize :layout

  before_save :assign_uuids

  SUBMODULE_TYPES = {
    'Article' => 'article',
    'Image' => 'img',
    'Image without caption' => 'img_nocaption',
  }

  ROW_TYPES = {
    "1-1-1-1" => '1,1,1,1',
    "2-1-1" => '2,1,1',
    "1-2-1" => '1,2,1',
    "1-1-2" => '1,1,2',
    "3-1" => '3,1',
    "1-3" => '1,3',
    "2-2" => '2,2',
    "4" => '4'
  }

  enum status: [:draft, :publish_ready, :published]

  def self.generate_uuid
    SecureRandom.uuid
  end

  def self.latest_published
    self.published.order('created_at DESC').first
  end

  def fold_article_ids
    output = []
    self.layout.each do |r|
      r[:modules].each do |m|
        m[:submodules].each do |s|
          output << s[:article_id].to_i if s[:type] == 'article'
        end
      end
    end
    output.uniq
  end

  def fold_image_ids
    output = []
    self.layout.each do |r|
      r[:modules].each do |m|
        m[:submodules].each do |s|
          output << s[:image_id] if (s[:type] == 'img' || s[:type] == 'img_nocaption')
        end
      end
    end
    output.uniq
  end

  private
    def assign_uuids
      self.layout = self.layout.map(&:with_indifferent_access)

      self.layout.each do |row|
        row[:uuid] ||= generate_uuid

        row[:modules].each do |mod|
          mod[:uuid] ||= generate_uuid

          mod[:submodules].each do |submod|
            submod[:uuid] ||= generate_uuid
          end
        end
      end
    end

    def generate_uuid
      SecureRandom.uuid
    end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  before_action :set_homepage, except: [:index, :new_submodule_form, :new_row_form, :new_specific_submodule_form, :create_specific_submodule, :create_new_row]

  load_and_authorize_resource only: [:index, :show, :update, :duplicate, :publish]

  def index
    @title = "Homepages"
    @homepages = Homepage.order('created_at DESC').limit(100)
  end

  def show
    @title = "Homepage " + @homepage.id.to_s
    @homepage = Homepage.find(params[:id])
    @latest_issue = Issue.latest_published

    if @homepage.published? || @homepage.publish_ready?
      @homepage_warning = "Layout locked since it has already been marked ready for publication."
      @homepage_locked = true
    else
      @homepage_editing = true
    end

    gon.layout = @homepage.layout

    render 'frontend/homepage', layout: 'frontend'
  end

  def update
    @homepage = Homepage.find(params[:id])
    @homepage.update(
      layout: JSON.parse(params[:layout]),
      status: params[:status]
    )

    redirect_to homepage_path(@homepage), flash: {success: 'Successfully updated homepage. '}
  end

  def mark_publish_ready
    authorize! :ready, @homepage

    @homepage = Homepage.find(params[:id])
    @homepage.publish_ready!

    redirect_to homepage_path(@homepage), flash: {success: 'Successfully marked layout as publish ready. '}
  end

  def duplicate
    @homepage = Homepage.find(params[:id])

    nh = Homepage.create(layout: @homepage.layout)

    redirect_to homepage_path(nh), flash: {success: 'Successfully duplicated the layout. '}
  end

  def new_submodule_form
    @uuid = params[:module_uuid]

    respond_to do |f|
      f.js
    end
  end

  def new_row_form
    respond_to do |f|
      f.js
    end
  end

  def new_specific_submodule_form
    @uuid = params[:uuid]
    @mod_uuid = params[:mod_uuid]
    @type = params[:type]

    respond_to do |f|
      f.js
    end
  end

  def create_specific_submodule
    @type = params[:type]
    @uuid = params[:uuid]
    @mod_uuid = params[:mod_uuid]

    sub_params = params[:submodule]

    m = {uuid: @uuid, type: @type}

    case @type.to_sym
    when :article
      m[:article_id] = sub_params[:article_id]
    when :img, :img_nocaption
      m[:image_id] = sub_params[:image_id]
    end

    @homepage_editing = true
    @content = render_to_string(partial: 'frontend/homepage/modules/submodule', locals: {m: m})
    @json = m.to_json

    respond_to do |f|
      f.js
    end
  end

  def create_new_row
    @uuid = params[:uuid]
    @type = params[:type].split(',').map(&:to_i)

    row = {
      uuid: @uuid,
      modules: @type.map do |c|
        {
          uuid: Homepage.generate_uuid,
          cols: c,
          submodules: []
        }
      end
    }

    @homepage_editing = true
    @content = render_to_string(partial: 'frontend/homepage/row', locals: {row: row})
    @json = row.to_json

    respond_to do |f|
      f.js
    end
  end

  def publish
    require 'varnish/purger'

    @homepage.published!
    Varnish::Purger.purge(root_path, true)

    redirect_to publishing_dashboard_path, flash: {success: "You have successfully published the homepage layout. "}
  end

  private
    def set_homepage
      @homepage = Homepage.find(params[:id])
    end
end

app/views/homepages/_master_editing_toolbar.html.erb
<div class="master-editing-toolbar">
  <% if @homepage_editing %>
    <%= form_tag homepage_path(homepage), method: :patch, id: 'save_layout_form' do %>
      <%= hidden_field_tag :layout %>

      <% if can? :update, Homepage %>
        <%= link_to 'Save Layout', '', id: 'save_layout' %>
      <% end %>
    <% end %>

    <%= form_tag homepage_path(homepage), method: :patch, id: 'mark_publish_ready_form' do %>
      <%= hidden_field_tag :layout %>
      <%= hidden_field_tag :status, 'publish_ready' %>

      <% if can? :ready, Homepage %>
        <%= link_to 'Mark as Publish Ready', '', id: 'mark_publish_ready' %>
      <% end %>
    <% end %>
  <% end %>

  <% if can? :duplicate, Homepage %>
    <%= link_to 'Duplicate this Layout', duplicate_homepage_path(homepage), method: :post %>
  <% end %>

  <%= link_to 'Back to Layout List', homepages_path %>

  <% if flash && flash[:success] %>
    <span class="flash success"><%= flash[:success] %></span>
  <% end %>

  <% if @homepage_warning %>
    <span class="flash warning"><%= @homepage_warning %></span>
  <% end %>
</div>

app/views/homepages/_new_row_form.html.erb
<% uuid = Homepage.generate_uuid %>
<div class="new-row-form" data-uuid="<%= uuid %>">
  <%= form_tag create_new_row_homepages_path, remote: true do %>
    <%= hidden_field_tag :uuid, uuid %>

    <%= select_tag :type, options_for_select(Homepage::ROW_TYPES.map { |k, v| [k, v] }) %>

    <%= submit_tag 'Add New Row' %>
  <% end %>
</div>

app/views/homepages/_new_row_toolbar.html.erb
<div class="new-row-toolbar">
  <%= link_to 'Add New Row', new_row_form_homepages_path, remote: true %>
</div>

app/views/homepages/_new_submodule_form.html.erb
<% uuid = Homepage.generate_uuid %>
<div class="new-submodule-form" data-uuid="<%= uuid %>">
  <%= form_tag new_specific_submodule_form_homepages_path, remote: true do %>
    <%= hidden_field_tag :uuid, uuid %>
    <%= hidden_field_tag :mod_uuid, @uuid %>
    <%= select_tag :type, options_for_select(Homepage::SUBMODULE_TYPES.map { |k, v| [k, v] }) %>

    <%= submit_tag 'Add Submodule' %>
  <% end %>
</div>

app/views/homepages/_row_editing_toolbar.html.erb
<div class="row-editing-toolbar">
  <%= link_to "javascript: window.homepage.remove_row('#{row[:uuid]}'); ", data: {confirm: 'Do you really want to remove this entire row? '} do %>
    <i class="fa fa-times"></i>
  <% end %>

  <%= link_to "javascript: window.homepage.move_row_upward('#{row[:uuid]}'); " do %>
    <i class="fa fa-arrow-up"></i>
  <% end %>

  <%= link_to "javascript: window.homepage.move_row_downward('#{row[:uuid]}'); " do %>
    <i class="fa fa-arrow-down"></i>
  <% end %>
</div>

app/views/homepages/create_new_row.js.erb
$('[data-uuid=<%= @uuid %>]').replaceWith('<%=j @content %>');
window.homepage.append_row(<%= raw(@json) %>);

app/views/homepages/create_specific_submodule.js.erb
$('[data-uuid=<%= @uuid %>]').replaceWith("<%=j @content %>");
window.homepage.append_submodule("<%=j @mod_uuid %>", <%= raw(@json) %>);

app/views/homepages/duplicate.html.erb
<div class="page-header">
  <h1>Homepages#duplicate</h1>
</div>
<p>Find me in app/views/homepages/duplicate.html.erb</p>

app/views/homepages/index.haml
.titleline
  %h1 Homepage Layouts
%table.table
  %thead
    %tr
      %th #
      %th.center Published?
      %th.center Publish Ready?
      %th Created At
      %th Last Modified At
      %th{colspan: 2}
  %tbody
    - @homepages.each do |h|
      %tr
        %td= h.id
        %td.center= link_to 'Yes', root_path if h.published?
        %td.center= 'Yes' if h.publish_ready?
        %td
          = time_ago_in_words h.created_at.to_s
          ago
        %td
          = time_ago_in_words h.updated_at.to_s
          ago
        %td= link_to 'View & Edit', homepage_path(h)
        %td
          - if can? :duplicate, Homepage
            = link_to 'Duplicate', duplicate_homepage_path(h), method: :post

app/views/homepages/new_row_form.js.erb
$('.new-row-toolbar').before("<%=j render 'new_row_form' %>");

app/views/homepages/new_specific_submodule_form.js.erb
$('[data-uuid=<%= @uuid %>]').html("<%=j render 'homepages/modules/forms/' + @type, uuid: @uuid, mod_uuid: @mod_uuid %>");

app/views/homepages/new_submodule_form.js.erb
$('.module[data-uuid=<%= @uuid %>] div:last').before('<%=j render "new_submodule_form" %>');