config/routes.rb
Rails.application.routes.draw do

  ##############################################################################
  # Frontend routes
  ##############################################################################

  # Homepage
  root 'frontend#homepage'

  # Article
  get '/:year/:month/:day/:slug' => 'frontend#article', as: 'frontend_article', action: 'show', constraints: {
    year: /\d{4}/,
    month: /\d{2}/,
    day: /\d{2}/
  }

  # Image
  get '/photos/:id' => 'frontend#image', as: 'frontend_image', action: 'show'

  get '/photos/(:volume)/(:number)' => 'frontend#images', as: 'frontend_images', constraints: {
    volume: /\d+/,
    number: /\d+/
  }

  # Section
  get '/:slug(/page/:page)' => 'frontend#section', as: 'frontend_section', constraints: {
    slug: /(news|world-and-nation|opinion|arts|sports|campus-life|fun|science)/
  }

  # Author
  get '/authors/:slug' => 'frontend#author', as: 'frontend_author'

  # Photo
  get '/photographers/:slug' => 'frontend#photographer', as: 'frontend_photographer'
  # Photo submission link temporary redirect
  get '/submitphoto', to: redirect('https://www.dropbox.com/request/DRmRaJGEr7LfVXUG2FHf', status: 302)
  # Caption submission link temporary redirect
  get '/submitcaption', to: redirect('https://docs.google.com/spreadsheets/d/1aoRyGfaOIK9WIMaktEO9G_LAyBKHs8VCPnMBVVhtyDs/edit?usp=sharing', status: 302)

  # Tag
  get '/tags/:slug(/:page)' => 'frontend#tag', as: 'frontend_tag'

  # Issue index and issue
  get '/issues' => 'frontend#issue_index', as: 'frontend_issue_index'
  get '/issues/(:volume)/(:number)' => 'frontend#issue', as: 'frontend_issue', constraints: {
    volume: /\d+/,
    number: /\d+/
  }
  get '/issues/(:volume)/(:number)/pdf' => 'frontend#issue_pdf', as: 'frontend_issue_pdf', constraints: {
    volume: /\d+/,
    number: /\d+/
  }

  # Ads manifest and relay
  get '/niceties/manifest' => 'frontend#ads_manifest', as: 'frontend_ads_manifest'
  get '/niceties/:id' => 'frontend#ads_relay', constraints: {id: /\d+/}, as: 'frontend_ads_relay'

  # RSS feed
  get '/feed' => 'frontend#feed', as: 'frontend_feed', defaults: {format: 'rss'}

  # Search
  get '/search/:type/(:query)(/page/:page)' => 'frontend#search', as: :frontend_search, defaults: {type: :articles}

  get '/:section_name/:id(/:slug)', controller: 'frontend_pieces', action: 'show_old_url', constraints: {id: /\d+/, section_name: /(news|world-and-nation|opinion|arts|sports|campus-life|fun|science)/}

  get '/:volume/:number/:archivetag' => 'frontend#legacy_article', constraints: {volume: /V\d+/, number: /N\d+/, archivetag: /[^\/]*\.html/}
  get '/:volume/:number/:parent/:archivetag' => 'frontend#legacy_article', constraints: {volume: /V\d+/, number: /N\d+/, parent: /.*/, archivetag: /.*\.html/}

  get '/:name', controller: 'frontend_static_pages', action: 'show', as: 'frontend_static_page', constraints: {name: /(ads(\/(index|schedule|policies|payment|adscontact))?)|(about(\/(index|contact|opinion_policy|comments|unpublish|copyright|publication_schedule|subscribe|special_projects|sponsors|donate|join|staff))?)/}

  get '/ads/adinfo', controller: 'frontend_static_pages', action: 'adinfo'
  get '/ads/adinfo/:advertiser_type', controller: 'frontend_static_pages', action: 'adinfo', as: 'frontend_adinfo', constraints: {advertiser_type: /[^.]*/}

  post '/update_mast', controller: 'frontend_static_pages', action: 'update_mast'

  ##############################################################################
  # API routes
  ##############################################################################

  namespace :api do
    get 'issue_lookup/:volume/:issue', action: 'issue_lookup'
    get 'article_as_xml/:id', action: 'article_as_xml'
    get 'newest_issue'
    get 'article_parts'
    get 'style_mapping'
  end

  ##############################################################################
  # Backend routes
  ##############################################################################

  scope '/admin' do
    if ENV['MAINTENANCE'].present?
      match '*path', via: [:get, :post, :patch, :delete, :put], to: 'static_pages#maintenance'
      match '/', via: [:get, :post, :patch, :delete, :put], to: 'static_pages#maintenance'
    end

    get '/', to: 'static_pages#admin_homepage', as: :admin_root

    resources :ads

    resources :homepages, only: [:index, :show, :update] do
      member do
        post 'mark_publish_ready'
        post 'duplicate'
        post 'publish'
      end

      collection do
        get 'new_submodule_form'
        get 'new_row_form'
        post 'new_specific_submodule_form'
        post 'create_specific_submodule'
        post 'create_new_row'
      end
    end

    resources :issues, only: [:index, :show, :create] do
      member do
        get 'upload_pdf_form'
        post 'upload_pdf'
        delete 'remove_pdf'
      end
    end

    resources :authors, only: [:new, :create, :edit, :update, :show, :index]

    resources :sections, only: [:new, :create, :edit, :update, :show, :index]

    resources :images, only: [:new, :create, :edit, :update, :destroy, :show, :index] do
      member do
        post 'publish'
        post 'unpublish'
        patch 'add_article'
        patch 'remove_article'
      end
    end

    resources :articles, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :drafts, only: [:index, :show, :update] do
        member do
          get 'revert'
          post 'publish'
          get 'below_fold_preview'
        end
      end

      member do
        patch 'update_rank'
        post 'unpublish'
      end

      collection do
        get 'below_fold_preview', controller: 'article_versions', action: 'below_fold_preview'
      end
    end

    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
    resources :users, only: [:index, :show, :edit, :update]

    get '/publish', controller: 'publishing', action: 'dashboard', as: 'publishing_dashboard'
    post '/publish', controller: 'publishing', action: 'publish'
  end
end

app/models/issue.rb
class Issue < AbstractModel
  has_many :legacy_pages

  has_many :articles, dependent: :destroy
  has_many :images, dependent: :destroy

  has_attached_file :pdf
  has_attached_file :pdf_preview, :styles => {
    :medium => "600x600>"
  }

  validates :volume, presence: true, numericality: {only_integer: true, greater_than: 0}
  validates :number, presence: true, numericality: {only_integer: true, greater_than: 0}, uniqueness: {scope: :volume, message: 'should be unique within a volume. '}
  validates :published_at, presence: true
  validates_attachment :pdf, :content_type => { :content_type => %w(application/pdf) }
  validates_attachment_content_type :pdf_preview, :content_type => /\Aimage\/.*\Z/

  default_scope { order('published_at DESC') }

  scope :published, -> { where('published_at <= ?', Time.now) }

  # Returns a user-friendly string representation of the name of this issue.
  def name
    "Volume #{volume} Issue #{number}"
  end

  def short_name
    "V#{volume} N#{number}"
  end

  # Return the issues grouped by volumes
  def self.volumes
    self.all.group_by(&:volume)
  end

  def self.latest_published
    Issue.published.first
  end

  def published_at=(date)
     begin
       parsed = Date.strptime(date,'%m/%d/%Y')
       super parsed
     rescue
       super date
     end
  end

  def generate_pdf_preview!
    return unless self.pdf.exists?

    begin
      require 'rmagick'
      require 'open-uri'

      tmp_pdf_file = '/tmp/pdf_preview.pdf'
      tmp_png_file = '/tmp/pdf_preview.png'

      tmp_pdf = File.open(tmp_pdf_file, 'wb')
      tmp_pdf.write(Paperclip.io_adapters.for(self.pdf).read)
      tmp_pdf.close

      im = Magick::ImageList.new(tmp_pdf_file)
      im[0].write tmp_png_file

      self.pdf_preview = File.open(tmp_png_file)
      self.save
    rescue Exception
    end
  end

  def as_react(ability)
    (self.as_json only: [:id]).merge({
      short_name: self.short_name
    })
  end

  # TODO: Created specifically for _article_select.html.erb
  # Would rather not have
  def published_articles
    self.articles.web_published
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  load_and_authorize_resource

  respond_to :html

  def index
    @title = "Issues"
    @filter_volume = params[:filter_volume]
    @issues = Issue.all
    @issues = @issues.where(volume: @filter_volume) if @filter_volume.present?
    @issues = @issues.page(params[:page]).per(100)

    @new_issue = Issue.new
  end

  def show
    @title = "V" + @issue.volume.to_s + " N" + @issue.number.to_s 
    @articles_by_sections = @issue.articles.reorder('section_id ASC').group_by { |x| x.section.name }
    @images = @issue.images
  end

  def create
    @issue = Issue.new(issue_params)

    if @issue.save
      redirect_to issues_path, flash: {success: 'Successfully created issue. '}
    else
      redirect_to issues_path, flash: {error: @issue.errors.full_messages.join("\n")}
    end
  end

  def upload_pdf
    @issue.pdf = params[:content]

    if @issue.valid?
      @issue.save
      @issue.generate_pdf_preview!

      redirect_to issues_path, flash: {success: "Successfully uploaded PDF for #{@issue.name}. "}
    else
      redirect_to issues_path, flash: {error: "Please make sure the file you upload is a valid PDF file. "}
    end
  end

  def upload_pdf_form
  end

  def remove_pdf
    @issue.pdf = nil
    @issue.save

    redirect_to issues_path, flash: {success: "Successfully removed PDF for #{@issue.name}. "}
  end

  private
    def set_issue
      @issue = Issue.find(params[:id])
    end

    def issue_params
      params.require(:issue).permit(:number, :volume, :published_at)
    end
end

app/views/issues/_upload_pdf_form.html.erb
<%= form_tag upload_pdf_issue_path(issue), multipart: true do %>
  <span class="btn btn-info btn-file upload_pdf">
    Upload <%= file_field_tag "content", type: :file, multiple: true, onchange: '$(this).parents("form").submit()' %>
  </span>
<% end %>

app/views/issues/index.haml
.titleline
  %h1
    - if @filter_volume
      Issues in Volume #{@filter_volume}
    - else
      Issues
  = form_tag issues_path, method: :get, name: 'filter_issues' do
    = select_tag :filter_volume, options_for_select([['All Volumes', '']] + Issue.volumes.collect { |k, v| ["Volume #{k}", k] }, @filter_volume), class: 'form-control'
%table.table
  %thead
    %tr
      %th Volume
      %th Number
      %th Published On
      %th PDF
      %th Details
  %tbody
    - if can? :create, Issue
      %tr
        = form_for @new_issue do |f|
          %td= f.text_field :volume, class: 'form-control', placeholder: 'Volume number'
          %td= f.text_field :number, class: 'form-control', placeholder: 'Issue number'
          %td= f.text_field :published_at, class: 'form-control', placeholder: 'Published date, MM/DD/YYYY', data: {provide: 'datepicker'}
          %td{:colspan => "2"}= f.submit 'Create Issue', id: 'create_issue', class: 'btn btn-primary'
    - can_upload_pdf = (can? :upload_pdf, @issues.first)
    - can_remove_pdf = (can? :remove_pdf, @issues.first)
    = content_tag_for(:tr, @issues.sort { |x,y| y <=> x }) do |issue|
      %td= issue.volume
      %td= issue.number
      %td= issue.published_at.try(:to_s, :long)
      %td{:id => "issue_#{issue.id}_upload_pdf"}
        - if issue.pdf.present?
          = link_to 'View PDF', issue.pdf.url
          - if can_remove_pdf
            = link_to 'Remove PDF', remove_pdf_issue_path(issue), data: {confirm: 'Do you really want to remove the uploaded PDF? '}, method: :delete
        - else
          - if can_upload_pdf
            = link_to 'Upload', upload_pdf_form_issue_path(issue), remote: true
      %td= link_to 'Details', issue_path(issue)
= paginate @issues, theme: 'twitter-bootstrap-3'

app/views/issues/show.haml
.titleline
  %h1= @issue.name
  = link_to issues_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list
    Back
- @articles_by_sections.each do |sec, articles|
  %h2= sec
  = render 'articles/article_list', articles: articles.sort_by(&:rank), hide_search: true, rank_select: true, from_issues_page: @issue.id
- if @images.any?
  %h2 Images
  = render 'images/image_list', images: @images, hide_search: true

app/views/issues/upload_pdf_form.js.erb
$('#issue_<%= @issue.id %>_upload_pdf').html("<%=j render 'upload_pdf_form', issue: @issue %>")