config/routes.rb
Rails.application.routes.draw do

  ##############################################################################
  # Frontend routes
  ##############################################################################

  # Homepage
  root 'frontend#homepage'

  # Article
  get '/:year/:month/:day/:slug' => 'frontend#article', as: 'frontend_article', action: 'show', constraints: {
    year: /\d{4}/,
    month: /\d{2}/,
    day: /\d{2}/
  }

  # Image
  get '/photos/:id' => 'frontend#image', as: 'frontend_image', action: 'show'

  get '/photos/(:volume)/(:number)' => 'frontend#images', as: 'frontend_images', constraints: {
    volume: /\d+/,
    number: /\d+/
  }

  # Section
  get '/:slug(/page/:page)' => 'frontend#section', as: 'frontend_section', constraints: {
    slug: /(news|world-and-nation|opinion|arts|sports|campus-life|fun|science)/
  }

  # Author
  get '/authors/:slug' => 'frontend#author', as: 'frontend_author'

  # Photo
  get '/photographers/:slug' => 'frontend#photographer', as: 'frontend_photographer'
  # Photo submission link temporary redirect
  get '/submitphoto', to: redirect('https://www.dropbox.com/request/DRmRaJGEr7LfVXUG2FHf', status: 302)
  # Caption submission link temporary redirect
  get '/submitcaption', to: redirect('https://docs.google.com/spreadsheets/d/1aoRyGfaOIK9WIMaktEO9G_LAyBKHs8VCPnMBVVhtyDs/edit?usp=sharing', status: 302)

  # Tag
  get '/tags/:slug(/:page)' => 'frontend#tag', as: 'frontend_tag'

  # Issue index and issue
  get '/issues' => 'frontend#issue_index', as: 'frontend_issue_index'
  get '/issues/(:volume)/(:number)' => 'frontend#issue', as: 'frontend_issue', constraints: {
    volume: /\d+/,
    number: /\d+/
  }
  get '/issues/(:volume)/(:number)/pdf' => 'frontend#issue_pdf', as: 'frontend_issue_pdf', constraints: {
    volume: /\d+/,
    number: /\d+/
  }

  # Ads manifest and relay
  get '/niceties/manifest' => 'frontend#ads_manifest', as: 'frontend_ads_manifest'
  get '/niceties/:id' => 'frontend#ads_relay', constraints: {id: /\d+/}, as: 'frontend_ads_relay'

  # RSS feed
  get '/feed' => 'frontend#feed', as: 'frontend_feed', defaults: {format: 'rss'}

  # Search
  get '/search/:type/(:query)(/page/:page)' => 'frontend#search', as: :frontend_search, defaults: {type: :articles}

  get '/:section_name/:id(/:slug)', controller: 'frontend_pieces', action: 'show_old_url', constraints: {id: /\d+/, section_name: /(news|world-and-nation|opinion|arts|sports|campus-life|fun|science)/}

  get '/:volume/:number/:archivetag' => 'frontend#legacy_article', constraints: {volume: /V\d+/, number: /N\d+/, archivetag: /[^\/]*\.html/}
  get '/:volume/:number/:parent/:archivetag' => 'frontend#legacy_article', constraints: {volume: /V\d+/, number: /N\d+/, parent: /.*/, archivetag: /.*\.html/}

  get '/:name', controller: 'frontend_static_pages', action: 'show', as: 'frontend_static_page', constraints: {name: /(ads(\/(index|schedule|policies|payment|adscontact))?)|(about(\/(index|contact|opinion_policy|comments|unpublish|copyright|publication_schedule|subscribe|special_projects|sponsors|donate|join|staff))?)/}

  get '/ads/adinfo', controller: 'frontend_static_pages', action: 'adinfo'
  get '/ads/adinfo/:advertiser_type', controller: 'frontend_static_pages', action: 'adinfo', as: 'frontend_adinfo', constraints: {advertiser_type: /[^.]*/}

  post '/update_mast', controller: 'frontend_static_pages', action: 'update_mast'

  ##############################################################################
  # API routes
  ##############################################################################

  namespace :api do
    get 'issue_lookup/:volume/:issue', action: 'issue_lookup'
    get 'article_as_xml/:id', action: 'article_as_xml'
    get 'newest_issue'
    get 'article_parts'
    get 'style_mapping'
  end

  ##############################################################################
  # Backend routes
  ##############################################################################

  scope '/admin' do
    if ENV['MAINTENANCE'].present?
      match '*path', via: [:get, :post, :patch, :delete, :put], to: 'static_pages#maintenance'
      match '/', via: [:get, :post, :patch, :delete, :put], to: 'static_pages#maintenance'
    end

    get '/', to: 'static_pages#admin_homepage', as: :admin_root

    resources :ads

    resources :homepages, only: [:index, :show, :update] do
      member do
        post 'mark_publish_ready'
        post 'duplicate'
        post 'publish'
      end

      collection do
        get 'new_submodule_form'
        get 'new_row_form'
        post 'new_specific_submodule_form'
        post 'create_specific_submodule'
        post 'create_new_row'
      end
    end

    resources :issues, only: [:index, :show, :create] do
      member do
        get 'upload_pdf_form'
        post 'upload_pdf'
        delete 'remove_pdf'
      end
    end

    resources :authors, only: [:new, :create, :edit, :update, :show, :index]

    resources :sections, only: [:new, :create, :edit, :update, :show, :index]

    resources :images, only: [:new, :create, :edit, :update, :destroy, :show, :index] do
      member do
        post 'publish'
        post 'unpublish'
        patch 'add_article'
        patch 'remove_article'
      end
    end

    resources :articles, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :drafts, only: [:index, :show, :update] do
        member do
          get 'revert'
          post 'publish'
          get 'below_fold_preview'
        end
      end

      member do
        patch 'update_rank'
        post 'unpublish'
      end

      collection do
        get 'below_fold_preview', controller: 'article_versions', action: 'below_fold_preview'
      end
    end

    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
    resources :users, only: [:index, :show, :edit, :update]

    get '/publish', controller: 'publishing', action: 'dashboard', as: 'publishing_dashboard'
    post '/publish', controller: 'publishing', action: 'publish'
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :prepare_authors_json, only: [:new, :edit]

  load_and_authorize_resource

  def index
    # Rough query syntax:
    #
    # If query looks like "  v343 N9394    " or "V134/N61" or "v100n1"
    #   then the articles from that issue are returned.
    # Otherwise
    #   articles are searched for matching headline or other metadata.

    @title = "Articles"
    @page = (params[:page].presence || 1).to_i

    puts "hi"
    puts params
    puts "query ^"
    if params[:q].blank?
      puts "hi2"
      respond_to do |f|
        puts f.json
        puts "hi2.5"
        f.html
        f.json do
          @articles = Article.order('created_at DESC').page(@page).per(20)
          puts "articles"
          puts @articles              

          next_page = @articles.last_page? ?
                      nil :
                      articles_path(page: @page + 1, format: :json)

          render json: {articles: @articles.map { |a| a.as_react(current_ability) }, nextPage: next_page}
        end
      end
    else
      puts "hi3"
      match = /^\s*V(\d+)[ \/]?N(\d+)\s*$/i.match(params[:q])
      unless match.nil?
        issue = Issue.find_by(volume: match[1].to_i, number: match[2].to_i)
        @articles = issue.articles rescue []
      else
        drafts = Draft.search_query(params[:q]).order('created_at DESC').limit(100)
        @articles = drafts.map(&:article).uniq
      end

      respond_to do |f|
        f.html
        f.json { render json: {articles: @articles.map { |a| a.as_react(current_ability) }, nextPage: nil} }
        f.js
      end
    end
  end

  def show
    respond_to do |f|
      f.json { render json: {article: @article.as_react(current_ability)} }
    end
  end

  def new
    @title = "New Article"
    @article = Article.new
    @draft = Draft.new
  end

  # This action creates BOTH a new Article, and a corresponding first Draft
  def create
    @article = Article.new(article_params)
    @draft = @article.drafts.build(draft_params)
    @draft.user = current_user

    if @article.valid? && @draft.valid?
      @article.save!
      @draft.save!

      redirect_to article_draft_path(@article, @draft), flash: {success: "You have successfully created an article. "}
    else
      @errors_compiled = @article.errors.full_messages + @draft.errors.full_messages

      if @errors_compiled.include? "Slug can't be blank"
        @errors_compiled.delete "Slug is too short (minimum is 5 characters)"
        @errors_compiled.delete "Slug is invalid"
      elsif @errors_compiled.include? "Slug is too short (minimum is 5 characters)"
        @errors_compiled.delete "Slug is invalid"
      end

      if @errors_compiled.include? "Headline can't be blank"
        @errors_compiled.delete "Headline is too short (minimum is 2 characters)"
      end

      @flash[:error] = (@errors_compiled).join("\n")
      prepare_authors_json
      render 'new'
    end
  end

  def edit
    @draft = @article.drafts.find(params[:draft_id])
    @title = "Edit '" + @draft.headline.split.first(2).join(' ') + "...'" # use first 2 words of last draft's headline in title
    gon.prefilled_authors = @draft.authors.map { |a| a.as_json(only: [:id, :name]) }
  end

  # This action modifies fields in a given Article object.
  # If params[:draft] is present, this action also creates a new Draft for the
  # given Article. This action NEVER mutates a Draft object.
  #
  # For changing a Draft object in-place, see drafts#update.
  def update
    @article.assign_attributes(article_params)
    @draft = @article.drafts.build(draft_params)
    @draft.user = current_user

    if @article.valid? && @draft.valid?
      @article.save!
      @draft.save!

      if !allowed_params[:update].nil?
        flash[:success] = "You have successfully updated the article. "
        return render js: "window.location = '#{article_draft_path(@article, @draft)}'; "
      end
    else
      @errors = (@article.errors.full_messages + @draft.errors.full_messages).join("\n")
    end
  end

  def update_rank
    @article.assign_attributes(article_params)
    @article.save!

    respond_to do |f|
      f.json { render json: {article: @article.as_react(current_ability)} }
    end
  end

  def destroy
    @article.destroy

    respond_to do |f|
      f.html { redirect_to :back, flash: {success: "You have successfully deleted the article. "} }
      f.json { render json: {article: {id: @article.id, destroyed: true}} }
    end
  end

  # TODO: Currently we publish Draft but unpublishes Article. Are we OCD enough to fix it?
  def unpublish
    @article.drafts.web_published.each do |article|
      article.web_ready!
    end

    # Invalidate below_fold fragment cache when new content is published/unpublished
    ActionController::Base.new.expire_fragment("below_fold")

    respond_to do |f|
      f.html { rediret_to :back, flash: {success: "You have successfully unpublished the article. "} }
      f.json { render json: {article: @article.as_react(current_ability)} }
    end
  end

  # TODO: Currently we publish Draft but unpublishes Article. Are we OCD enough to fix it?
  def unpublish
    @article.drafts.web_published.each do |article|
      article.web_ready!
    end

    respond_to do |f|
      f.html { rediret_to :back, flash: {success: "You have successfully unpublished the article. "} }
      f.js
    end
  end

  private
    def allowed_params
      params.permit(
        :save,
        :update,
        article: [:issue_id, :section_id, :slug, :syndicated, :allow_ads, :brief, :rank, :update, :save],
        draft: [:primary_tag, :secondary_tags, :headline, :subhead, :comma_separated_author_ids, :bytitle, :social_media_blurb, :sandwich_quotes, :attribution, :redirect_url, :lede, :html]
      )
    end

    def article_params
      allowed_params[:article]
    end

    def draft_params
      allowed_params[:draft]
    end

    def prepare_authors_json
      gon.authors = Author.all.map { |a| {id: a.id, name: a.name} }
    end
end

app/views/articles/_article_list.haml
= react_component "ArticleList", articles: articles.map { |a| a.as_react(current_ability) },    |
                                 fetch: local_assigns[:fetch],                                  |
                                 hideSearch: local_assigns[:hide_search],                       |
                                 rankSelect: local_assigns[:rank_select],                       |
                                 from_issues_page: local_assigns[:from_issues_page]
= react_component "TestComponent"

app/views/articles/_form.haml
#newAuthorModal.modal.fade{"aria-hidden" => "true", role: "dialog", tabindex: "-1"}
  = form_for Author.new, remote: true do |f|
    .modal-dialog{role: "document"}
      .modal-content
        .modal-header
          %h5.modal-title Create New Author
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", type: "button"}
            %span{"aria-hidden" => "true"} ×
        .modal-body
          .form-group
            = f.text_field :name, placeholder: 'Name', class: 'form-control'
          .form-group
            = f.text_field :email, placeholder: 'Email (optional)', class: 'form-control'
          .form-group
            = f.text_field :twitter, placeholder: 'Twitter (optional)', class: 'form-control'
          .form-group
            = f.text_area :bio, placeholder: 'Bio information (optional)', class: 'form-control'
        .modal-footer
          %button.btn.btn-secondary{"data-dismiss" => "modal", type: "button"} Close
          = f.button 'Create', class: 'btn btn-primary', data: {disable_with: loading_icon}


= form_for article, remote: !article.new_record? do |f|
  = fields_for draft do |df|
    .row
      / REBIRTH_TODO: BTF preview
      .col-lg-8
        .row
          .col-md-12
            .form-group
              = df.text_field :headline, placeholder: 'Headline of the article (in sentence case without trailing period)', class: 'form-control', data: {smart_quotes: true}, autocomplete: 'off'
        .row
          .col-md-12
            .form-group
              = df.text_field :subhead, placeholder: 'Subhead of the article (in sentence case without trailing period)', class: 'form-control', data: {smart_quotes: true}, autocomplete: 'off'
        .row
          .col-md-12
            .form-group
              = df.text_area :html, class: 'form-control ckeditor'
        .row
          .col-sm-12
            .actions
              - if article.new_record?
                = f.submit 'Create Article', class: 'btn btn-primary'
              - else
                = f.button 'Update and Preview', class: 'btn btn-primary', data: {disable_with: loading_icon}, name: 'update'
                = f.button 'Save', class: 'btn btn-success', data: {disable_with: loading_icon}, name: 'save'
      .col-lg-4
        .well
          .row
            .col-md-12
              .form-group
                = f.label :slug, 'Slug (public-facing URL component)'
                = f.text_field :slug, class: 'form-control', placeholder: 'e.g., example-slug-of-interesting-article', disabled: article.has_web_published_draft?
          .row
            .col-md-12
              .form-group
                - if article.issue.nil?
                  = f.select :issue_id, options_from_collection_for_select(Issue.limit(10), :id, :name, article.issue_id), {}, {class: 'form-control'}
                - else
                  = f.select :issue_id, options_from_collection_for_select(Issue.limit(10).append(article.issue), :id, :name, article.issue_id), {}, {class: 'form-control'}
          .row
            .col-md-12
              .form-group
                = f.select :section_id, options_from_collection_for_select(Section.all, :id, :name, article.section_id), {}, {class: 'form-control'}
          .row
            .col-md-12
              .checkbox
                = f.label :syndicated do
                  = f.check_box :syndicated, data: {hide_trigger: 'syndicated'}
                  This is a syndicated article.
              .checkbox
                = f.label :allow_ads do
                  = f.check_box :allow_ads
                  Allow ads to be displayed on this article.
              .checkbox
                = f.label :brief do
                  = f.check_box :brief
                  This is a brief article.
          - unless article.new_record?
            %p.form-comment Changes here take effect upon being saved.
        .well
          .row
            .col-md-12
              .form-group
                = df.label :primary_tag, 'Primary Tag'
                = df.text_field :primary_tag, placeholder: 'e.g., THEATER REVIEW', class: 'form-control'
          .row
            .col-md-12
              .form-group
                = df.label :secondary_tag, 'Other Tags (comma-separated)'
                = df.text_field :secondary_tags, class: 'form-control', data: {role: 'tagsinput'}
          .row{'data-hide-on' => 'syndicated'}
            .col-md-12
              .form-group
                = df.label :comma_separated_author_ids, 'Authors'
                = link_to 'Create New', '#', class: 'float-right', tabindex: 0, data: {toggle: 'modal', target: "#newAuthorModal"}
                = df.text_field :comma_separated_author_ids, class: 'form-control'
          .row{'data-hide-on' => 'syndicated'}
            .col-md-12
              .form-group
                = df.label :bytitle, 'Bytitle'
                = df.text_field :bytitle, placeholder: 'e.g., News Editor', class: 'form-control'
          .row{'data-hide-on' => 'syndicated'}
            .col-md-12
              .form-group
                = df.label :lede, "Teaser blurb"
                = df.text_area :lede, placeholder: 'Brief introduction of the article that appears on homepage, search page, etc.', class: 'form-control'
          .row{'data-hide-on' => 'syndicated'}
            .col-md-12
              .form-group
                = df.label :social_media_blurb, 'Social Media Blurb'
                = df.text_area :social_media_blurb, placeholder: 'Brief description of the article for our social media pages', class: 'form-control'
          .row{'data-hide-on' => 'syndicated'}
            .col-md-12
              .form-group
                = df.label :sandwich_quotes,  'Sandwich Quotes'
                = df.text_area :sandwich_quotes, placeholder: 'Filler quotes for Prod', class: 'form-control'
          .row{'data-show-on' => 'syndicated'}
            .col-md-12
              .form-group
                = df.label :attribution, "Attribution line"
                = df.text_field :attribution, class: 'form-control'
          .row
            .col-md-12.text-right
              = link_to 'Show Advanced Fields', '', data: {'hide-trigger' => 'show_advanced', 'hide-value' => true, 'hide-on' => 'show_advanced'}
          .row{'data-show-on' => 'show_advanced'}
            .col-md-12
              .form-group
                = df.label :redirect_url, 'Redirect URL'
                = df.text_field :redirect_url, placeholder: 'Leave empty if not used', class: 'form-control'
          .row
            .col-md-12.text-right
              = link_to 'Hide Advanced Fields', '', data: {'hide-trigger' => 'show_advanced', 'hide-value' => false, 'show-on' => 'show_advanced'}
          - unless article.new_record?
            %p.form-comment Changes here require EIC approval.

app/views/articles/edit.haml
.titleline
  %h1 Edit Article
  = link_to articles_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back to Articles
  = link_to :back, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-chevron-left
    Back

= render 'form', article: @article, draft: @draft

app/views/articles/index.haml
.titleline
  %h1 Articles
  = link_to new_article_path, class: 'btn btn-primary', data: { no_turbolink: true } do
    %span.glyphicon.glyphicon-plus
    New Article
= render 'article_list', articles: [], fetch: articles_path(format: :json)

app/views/articles/new.haml
.titleline
  %h1 New Article
  = link_to articles_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back

= render 'form', article: @article, draft: @draft

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div id="piece_container">

  <header>
    <h1><%= @article.piece.title %></h1>

    <% unless @article.subhead.blank? %>
      <p id="subhead"><%= @article.subhead %></p>
    <% end %>

    <% unless @article.authors.empty? %>
      <p id="authors">By <%= @article.authors_line %></p>
    <% end %>

    <% unless @article.bytitle.blank? %>
      <p id="byline"><%= @article.bytitle %></p>
    <% end %>

    <p>
      <% for tag in @article.piece.tags %>
        <span class="label label-primary"><%= tag %></span>
      <% end %>
    </p>
  </header>

  <p class="intro">Intro: <%= @article.intro %></p>

  <%= @html.html_safe %>
</div>

<hr>

<%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-primary', data: {no_turbolink: true} %>
<%= link_to 'Back', articles_path, class: 'btn btn-default', data: {no_turbolink: true} %>
<%= link_to 'Download InCopy Tagged File', as_xml_article_path(@article), class: 'btn btn-default' %>

app/views/articles/unpublish.js.erb
$('#article_<%= @article.id %>').replaceWith("<%=j render 'articles/article', article: @article %>");

app/views/articles/update.js.erb
<% if @errors.present? %>
  alert("The article cannot be saved due to the following errors: \n" + "<%=j @errors.html_safe %>");
<% else %>
  history.pushState({}, null, "<%=j edit_article_url(@article, draft_id: @draft.id) %>");
<% end %>

app/views/articles/update_rank.js.erb
$("#update_rank_result_<%= @article.id %>").text('Success');